/**
 * M1b — recorded-case parity tests (SPEC §13.3 / §19 M1b acceptance).
 *
 * Loads FROZEN fixtures under tests/fixtures/ (generated by
 * scripts/gen-parity-fixtures.py from the REAL Xenoblade fork Python tools —
 * `tools/coop/extc.py` classify/plan + `member_check.classify_symbol`) and
 * asserts the TS ports reproduce the recorded Python verdicts, modulo the
 * documented deviation list in docs/m1b-parity.md:
 *
 *   1. TS `classifyExternC` (name category + member-candidate hint) ==
 *      extc.py `classify` + the member_candidates/jp_stale lists, on a
 *      us-region-only table (Python merges us+eu+reloc-map names — the
 *      fixtures use us only).
 *   2. TS `extractEntries` == extc.py `extract_entries` on the frozen real
 *      CTaskGameEvt.cpp source (including the reference's eaten-decl quirk).
 *   3. TS `planMemberConversion` hit list / retail symbols == extc.py `plan`;
 *      the per-def mangling target matches Python's `member_mangled` for
 *      plain methods, and is CANONICALIZED for `__ct__`/`__dt__` names
 *      (documented deviation — Python's naive `__ct__CExchangeWin__…` is not
 *      a valid MWCC ctor name).
 *   4. TS `classifyMember` kind + `verdictString` ==
 *      `member_check.classify_symbol` verdict string on the frozen real asm
 *      (ocCfp.s callers + the two 1-instruction stub bodies).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadSymbols, parseMangled } from "../src/parse/symbols/table.js";
import {
  classifyExternC,
  planMemberConversion,
  scanExternC,
} from "../src/parse/symbols/extc.js";
import { extractEntries } from "../src/parse/symbols/scanner.js";
import { parseAsmFile } from "../src/parse/asm/dtk.js";
import { classifyMember } from "../src/parse/asm/member.js";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const readFixture = (name: string): string =>
  readFileSync(join(FIXTURES, name), "utf8");

interface RecordedCase {
  name: string;
  category: "exact" | "drift" | "invented";
  resolved: string | null;
  jp_stale?: boolean;
}

interface RecordedEntry {
  lineno: number;
  name: string | null;
  raw: string;
  category: string;
  resolved: string | null;
  memberCandidateHint: boolean;
}

interface RecordedHit {
  lineno: number;
  name: string;
  kind: string;
  header: string;
}

interface RecordedRecipe {
  lineno: number;
  name: string;
  mangled: string;
}

test("parity: classifyExternC reproduces extc.py classify on recorded real names", () => {
  const table = loadSymbols(readFixture("parity-symbols.txt"));
  const fixture = JSON.parse(readFixture("parity-extc-scan.json")) as {
    cases: RecordedCase[];
  };
  for (const c of fixture.cases) {
    const r = classifyExternC({ name: c.name, params: [], line: 0 }, table);
    if (c.jp_stale === true) {
      // Python reports (exact, us) with a separate jp_stale record; TS folds
      // it into the jp_stale category (SPEC §13.3 extc.jp_stale_address)
      assert.equal(r.category.category, "jp_stale", c.name);
      if (r.category.category === "jp_stale") {
        assert.equal(r.category.name, c.name);
        assert.ok(r.category.resolved.length > 0);
      }
    } else {
      assert.equal(r.category.category, c.category, c.name);
      if (c.category === "drift" && r.category.category === "drift") {
        assert.equal(r.category.resolved, c.resolved, c.name);
      }
    }
  }
});

test("parity: scanner entries + classification on the frozen CTaskGameEvt.cpp source", () => {
  const table = loadSymbols(readFixture("parity-symbols.txt"));
  const fixture = JSON.parse(readFixture("parity-extc-scan.json")) as {
    source: string;
    source_path: string;
    sourceEntries: RecordedEntry[];
  };
  // 1) extractEntries reproduces the recorded (lineno, name, raw) list —
  // including the reference quirk that the decl directly after the
  // cbRenderBefore def is eaten
  const entries = extractEntries(fixture.source.split(/\r?\n/));
  assert.deepEqual(
    entries.map((e) => ({ lineno: e.lineno, name: e.name, raw: e.raw })),
    fixture.sourceEntries.map((e) => ({ lineno: e.lineno, name: e.name, raw: e.raw })),
  );
  assert.deepEqual(
    fixture.sourceEntries.map((e) => e.name),
    ["func_80295764"],
  );
  // 2) classifyExternC on each recorded entry reproduces the recorded
  // category + member-candidate hint
  const scanned = scanExternC(
    [{ path: fixture.source_path, text: fixture.source }],
    table,
  );
  assert.equal(scanned.length, fixture.sourceEntries.length);
  for (const s of scanned) {
    const rec = fixture.sourceEntries.find((e) => e.lineno === s.entry.lineno);
    assert.ok(rec, `no recorded entry for line ${s.entry.lineno}`);
    assert.equal(s.classification.category.category, rec!.category);
    assert.equal(s.classification.memberCandidateHint, rec!.memberCandidateHint);
  }
  // the recorded entry is the review's func_80295764 void* self DECL: exact
  // name + hint true (self-style)
  assert.equal(scanned[0]!.entry.name, "func_80295764");
  assert.equal(scanned[0]!.classification.category.category, "exact");
  assert.equal(scanned[0]!.classification.memberCandidateHint, true);
});

test("parity: planMemberConversion reproduces extc.py plan on frozen CExchangeWin.cpp", () => {
  const fixture = JSON.parse(readFixture("parity-extc-plan.json")) as {
    token: string;
    source: string;
    source_path: string;
    "symbols.txt": string;
    retail_symbols: string[];
    hits: RecordedHit[];
    recipe: RecordedRecipe[];
  };
  const table = loadSymbols(fixture["symbols.txt"]);
  const plan = planMemberConversion(
    fixture.token,
    table,
    [{ path: fixture.source_path, text: fixture.source }],
  );
  // retail_symbols: every retail name containing the token (Python class_syms)
  assert.deepEqual(plan.retailSymbols, fixture.retail_symbols);
  // hits: (line, name, kind, header) — exact Python parity
  assert.deepEqual(
    plan.hits.map((h) => ({ lineno: h.line, name: h.name, kind: h.kind, header: h.header })),
    fixture.hits,
  );
  // per-def targets: Python member_mangled verbatim for plain methods; the
  // `__ct__`/`__dt__` defs are CANONICALIZED (documented deviation — Python's
  // naive `__ct__CExchangeWin__12CExchangeWinFv` is not a valid MWCC ctor
  // name; see docs/m1b-parity.md)
  for (const t of plan.targets) {
    const rec = fixture.recipe.find((r) => r.lineno === t.line && r.name === t.name);
    assert.ok(rec, `no recorded recipe for ${t.name}`);
    assert.equal(t.mangled, rec!.mangled); // Python member_mangled parity
    if (t.name.startsWith("__ct__") || t.name.startsWith("__dt__")) {
      assert.notEqual(t.canonical, rec!.mangled); // canonicalized (deviation)
      assert.equal(t.canonical, t.name.startsWith("__ct__") ? "__ct__12CExchangeWinFv" : "__dt__12CExchangeWinFv");
    } else {
      assert.equal(t.canonical, rec!.mangled); // canonical == naive for methods
    }
  }
  // the recorded plan contains the review's void* self / typed-self defs
  assert.ok(plan.hits.some((h) => h.name === "__ct__CExchangeWin" && h.kind === "def-param"));
  assert.ok(plan.hits.some((h) => h.name === "func_8022D0A4" && h.kind === "def-param"));
});

test("parity: classifyMember reproduces member_check on frozen real asm (ocCfp.s)", () => {
  const fixture = JSON.parse(readFixture("parity-member.json")) as {
    symbols: Array<{
      symbol: string;
      call_sites: number;
      callers: Array<[string, string, number]>;
      r3_provenance: Record<string, number>;
      verdict: string;
      body_present: boolean;
    }>;
    "symbols.txt": string;
  };
  const table = loadSymbols(fixture["symbols.txt"]);
  const asm = parseAsmFile(readFixture("parity-member-asm.s"));
  for (const rec of fixture.symbols) {
    const v = classifyMember({
      asm,
      symbols: table,
      dataHits: [],
      targetSymbol: rec.symbol,
      classSize: 0,
    });
    // verdictString is the reference's EXACT verdict string (Python parity)
    assert.equal(v.verdict, "not_member", rec.symbol);
    assert.ok(v.reasons.some((e) => e === `verdict: not_member — ${rec.verdict}`), rec.symbol);
    // provenance evidence: recorded FILE-GLOBAL call-site index + r3 write
    // classification (CLRLWI), matching member_check.r3_provenance
    assert.ok(
      v.evidence.some((e) =>
        rec.callers.some(([, caller, i]) => e.includes(`call site 1: ${caller}@${i}`))
      ),
      `${rec.symbol}: call-site index parity`,
    );
    const provKey = Object.keys(rec.r3_provenance)[0];
    assert.ok(
      v.evidence.some((e) => e.includes(`r3 provenance: ${provKey}x1`)),
      rec.symbol,
    );
    assert.ok(v.evidence.some((e) => e === "body present: true"), rec.symbol);
  }
});

test("parity: parseMangled handles the recorded real symbols", () => {
  // the recorded @unnamed Q member parses as a member with a real className
  const m = parseMangled("wkUpdate__Q219@unnamed@CGame_cpp@12CGameRestartFv");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "CGameRestart");
});
