/**
 * M1b tests for the symbols.txt loader + MWCC mangled-name parser
 * (`src/parse/symbols/table.ts`): port of
 * `tools/symbolrecover/lib/parser.py` (load_symbols) and the `__Q…`
 * qualifier parsing in `tools/coop/member_check.py` against the real
 * `config/us/symbols.txt` format.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { loadSymbols, parseMangled } from "../src/parse/symbols/table.js";

const SNIPPET = `# generated by decomp-toolkit
memcpy = .init:0x80004000; // type:function size:0x29C scope:global
__start = .init:0x80006310; // type:function size:0x16C scope:weak

// extab data bucket
@4558 = extab:0x800066E0; // type:object size:0x1C scope:local hidden
func_80047814__Q22cf13CfObjectPointFv = .text:0x80047814; // type:function size:0x54 scope:global
func_80137038 = .text:0x80137038; // type:function size:0x1C scope:global
lbl_80137038 = .text:0x80137038; // type:label scope:local
tolerant_no_section = 0x80200000; // type:function
`;

test("loadSymbols: byAddress / byName lookups", () => {
  const t = loadSymbols(SNIPPET);
  assert.deepEqual(t.byAddress.get(0x80004000), ["memcpy"]);
  assert.equal(t.byName.get("memcpy"), 0x80004000);
  assert.deepEqual(t.byAddress.get(0x80047814), ["func_80047814__Q22cf13CfObjectPointFv"]);
  assert.equal(t.byName.get("__start"), 0x80006310);
  assert.deepEqual(t.byAddress.get(0x800066E0), ["@4558"]);
  // tolerant form without a section
  assert.equal(t.byName.get("tolerant_no_section"), 0x80200000);
  assert.deepEqual(t.byAddress.get(0x80200000), ["tolerant_no_section"]);
  // two names aliased to one address: byName keeps both (first wins), and
  // byAddress keeps ALL occupants in file order (Python addr_hits parity —
  // the func_X / lbl_X alias is what makes jp-stale detection correct)
  assert.equal(t.byName.get("func_80137038"), 0x80137038);
  assert.equal(t.byName.get("lbl_80137038"), 0x80137038);
  assert.equal(t.byName.size, 7);
  assert.equal(t.byAddress.size, 6);
  assert.deepEqual(t.byAddress.get(0x80137038), ["func_80137038", "lbl_80137038"]);
});

test("loadSymbols: byName is first-wins for duplicate names (setdefault parity)", () => {
  const t = loadSymbols("dup = .text:0x80004000;\ndup = .text:0x80005000;\n");
  // Python `names.setdefault(name, reg)` keeps the FIRST occurrence
  assert.equal(t.byName.get("dup"), 0x80004000);
  assert.deepEqual(t.byAddress.get(0x80004000), ["dup"]);
  assert.deepEqual(t.byAddress.get(0x80005000), ["dup"]);
});

test("loadSymbols: comments and blank lines are ignored", () => {
  const t = loadSymbols(
    "// a comment\n\n# another comment\n   \nmemcpy = .init:0x80004000;\nmemmove = .text:0x80000000 // no trailing semicolon\n",
  );
  assert.equal(t.byName.get("memcpy"), 0x80004000);
  assert.equal(t.byName.get("memmove"), 0x80000000);
  assert.deepEqual(t.byAddress.get(0x80004000), ["memcpy"]);
  assert.deepEqual(t.byAddress.get(0x80000000), ["memmove"]);
  assert.equal(t.byName.size, 2);
  assert.equal(t.byAddress.size, 2);
});

test("loadSymbols: malformed lines are skipped", () => {
  const t = loadSymbols("garbage line without equals\n= 0x80004000;\nmemcpy = 0x;\n");
  assert.equal(t.byName.size, 0);
  assert.equal(t.byAddress.size, 0);
});

test("parseMangled: __ct__ constructor", () => {
  const m = parseMangled("__ct__11CGameFv");
  assert.equal(m.isMember, true);
  assert.equal(m.isConstructor, true);
  assert.equal(m.isDestructor, false);
  assert.equal(m.className, "CGame");
  assert.equal(m.params, "v");
  assert.deepEqual(m.namespacePath, []);
});

test("parseMangled: __dt__ destructor", () => {
  const m = parseMangled("__dt__11CGameFv");
  assert.equal(m.isMember, true);
  assert.equal(m.isConstructor, false);
  assert.equal(m.isDestructor, true);
  assert.equal(m.className, "CGame");
  assert.equal(m.params, "v");
});

test("parseMangled: __Q scoped member of mtl::MemManager", () => {
  const m = parseMangled("__Q23mtl10MemManagerFv");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "MemManager");
  assert.deepEqual(m.namespacePath, ["mtl", "MemManager"]);
  assert.equal(m.params, "v");
});

test("parseMangled: func_XXXXXXXX is a free function, not a member", () => {
  const m = parseMangled("func_80137038");
  assert.equal(m.isMember, false);
  assert.equal(m.isConstructor, false);
  assert.equal(m.isDestructor, false);
  assert.equal(m.className, null);
  assert.equal(m.params, null);
  assert.deepEqual(m.namespacePath, []);
});

test("parseMangled: real-scope Q examples with params", () => {
  const m = parseMangled("func_80047814__Q22cf13CfObjectPointFv");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "CfObjectPoint");
  assert.deepEqual(m.namespacePath, ["cf", "CfObjectPoint"]);
  assert.equal(m.params, "v");

  const n = parseMangled("func_800694B0__Q22cf15CfScriptManagerFPCc");
  assert.equal(n.className, "CfScriptManager");
  assert.equal(n.params, "PCc");

  const o = parseMangled("ICulling_UnkVirtualFunc1__Q22cf12CTaskCullingFPQ22ml8CFrustum");
  assert.equal(o.className, "CTaskCulling");
  assert.deepEqual(o.namespacePath, ["cf", "CTaskCulling"]);
  assert.equal(o.params, "PQ22ml8CFrustum");
});

test("parseMangled: __ct__/__dt__ with real exact lengths", () => {
  const c = parseMangled("__ct__5CGameFPCcP11CWorkThread");
  assert.equal(c.isConstructor, true);
  assert.equal(c.className, "CGame");
  assert.equal(c.params, "PCcP11CWorkThread");

  const d = parseMangled("__dt__16CLibCriMoviePlayFv");
  assert.equal(d.isDestructor, true);
  assert.equal(d.className, "CLibCriMoviePlay");
  assert.equal(d.params, "v");

  const q = parseMangled("__dt__Q44nw4r3snd6detail9SeqPlayerFv");
  assert.equal(q.isDestructor, true);
  assert.equal(q.isMember, true);
  assert.equal(q.className, "SeqPlayer");
  assert.deepEqual(q.namespacePath, ["nw4r", "snd", "detail", "SeqPlayer"]);
  assert.equal(q.params, "v");
});

test("parseMangled: plain __<len> member methods", () => {
  const m = parseMangled("__11CGameFv");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "CGame");
  assert.equal(m.params, "v");

  const n = parseMangled("func_801A06F8__11COccCullingFUli");
  assert.equal(n.isMember, true);
  assert.equal(n.className, "COccCulling");
  assert.equal(n.params, "Uli");

  const o = parseMangled("func_8044E780__11CDeviceFileFv");
  assert.equal(o.className, "CDeviceFile");
  assert.equal(o.params, "v");
});

test("parseMangled: free names are not members", () => {
  for (const name of [
    "func_80137038",
    "lbl_80137038",
    "data_80006000",
    "memcpy",
    "__start",
    "__init_registers",
    "__sinit_CfGameManager_cpp",
    "__800B0AF4",
    "@4558",
    "@etb_800067C4",
    "gTRKInterruptVectorTable",
  ]) {
    const m = parseMangled(name);
    assert.equal(m.isMember, false, `${name} should be free`);
    assert.equal(m.className, null, `${name} should have no class`);
  }
});

test("parseMangled: anonymous-namespace qualifier is a real token (108/116 real @unnamed symbols)", () => {
  // dtk renders an anonymous namespace as `@unnamed@<file>_cpp@` INSIDE the
  // qualifier; only known dtk local suffixes (`@instance`, `@<digits>`) are
  // stripped before parsing, so the qualifier survives.
  const m = parseMangled("wkUpdate__Q219@unnamed@CGame_cpp@12CGameRestartFv");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "CGameRestart");
  assert.deepEqual(m.namespacePath, ["@unnamed@CGame_cpp@", "CGameRestart"]);
  assert.equal(m.params, "v");

  const d = parseMangled("__dt__Q219@unnamed@CGame_cpp@12CGameRestartFv");
  assert.equal(d.isMember, true);
  assert.equal(d.isDestructor, true);
  assert.equal(d.className, "CGameRestart");

  // unqualified anonymous-namespace class token: `__<len>@unnamed@…F<params>`
  const u = parseMangled("GetFreePlayer__24@unnamed@HBMAxSound_cpp@Fi");
  assert.equal(u.isMember, true);
  assert.equal(u.className, "@unnamed@HBMAxSound_cpp@");
  assert.equal(u.params, "i");
});

test("parseMangled: bucket prefixes and data members with @ tokens", () => {
  const m = parseMangled("@GUARD@mDefaultTagProcessor__Q36nw4hbm2ut17TextWriterBase<c>");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "TextWriterBase<c>");
  assert.deepEqual(m.namespacePath, ["nw4hbm", "ut", "TextWriterBase<c>"]);
  assert.equal(m.params, null);

  const n = parseMangled("@LOCAL@getInstance__Q22ml6MTRandFv@instance");
  assert.equal(n.isMember, true);
  assert.equal(n.className, "MTRand");
  assert.deepEqual(n.namespacePath, ["ml", "MTRand"]);
  assert.equal(n.params, "v");
});

test("parseMangled: dtk local suffixes (@instance, @<digits>) still stripped", () => {
  const m = parseMangled("@LOCAL@getInstance__Q22ml6MTRandFv@instance");
  assert.equal(m.isMember, true);
  assert.equal(m.className, "MTRand");
  assert.equal(m.params, "v");
  const b = parseMangled("wkUpdate__Q219@unnamed@CGame_cpp@12CGameRestartFv@4");
  assert.equal(b.isMember, true);
  assert.equal(b.className, "CGameRestart");
  assert.equal(b.params, "v");
});
